spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meituan?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    password: 707304
    username: root

server:
  port: 8888

mybatis-plus:
  configuration:
    use-deprecated-executor: false # ??????




